stages:
  - build
  - push
  - deploy

variables:
  # IMAGE_GROUP: xxx
  # NAME_SPACE: xxx
  # GOPATH: ${CI_PROJECT_DIR}/.go
  # GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  # GOCACHE: ${CI_PROJECT_DIR}/.go/.cache/go-build
  # GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/.go/.cache/golangci-lint

build:
  only:
    - main
  stage: build
  image: node:21 # 利用Golang容器进行打包Golang项目
  script:
    - yarn add typescript --dev
    - yarn
    - yarn build
    - rm -rf /data/artifacts/user_portal_dist
    - cp -r dist /data/artifacts/user_portal_dist

push:
  only:
    - main
  image: docker
  stage: push
  script:
    - rm -rf dist
    - cp -r /data/artifacts/user_portal_dist dist
    - docker build -t easzlab.io.local:5000/unibee/unibee-user-portal:daily .
    - docker push easzlab.io.local:5000/unibee/unibee-user-portal:daily

deploy:
  only:
    - main
  image: registry.cn-shenzhen.aliyuncs.com/heiku/kubectl:latest
  stage: deploy
  script:
    - kubectl --kubeconfig ${KUBE_FILE} rollout restart deployment/yd-oss-unib-user-protal-prod
    # - kubectl --kubeconfig ${KUBE_FILE} rollout status deployment/yd-oss-unib-user-protal-prod

hub_push:
  only:
    - main
  image: docker
  stage: hub_push
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker tag easzlab.io.local:5000/unibee/unibee-user-portal:daily unibee/user-portal:stage
    - docker push unibee/user-portal:stage