name: Release latest version

on:
  repository_dispatch:
    types: [release]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Tag version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          CUSTOM_TAG: ${{ github.event.client_payload.version }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.client_payload.version }}
          name: Release ${{ github.event.client_payload.version }}
          generateReleaseNotes: true
