name: Update package.json version

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Parse version
        id: parse_version
        run: |
          VERSION=${{ inputs.version }}
          echo "parsed_version=${VERSION:1}" >> "$GITHUB_OUTPUT"

      - name: Update package.json version
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq '.version = "${{ steps.parse_version.outputs.parsed_version }}"' package.json > tmp.json && mv tmp.json package.json

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'ci: update version to ${{ steps.parse_version.outputs.parsed_version }}'
          push: true
